application:
  alert-messages-topic: alerts
spring:
  kafka:
    bootstrap-servers:
      - localhost:3456
    producer:
      key-serializer: org.springframework.kafka.support.serializer.ToStringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer