application:
  alert-messages-topic: alerts
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alert-deduplication
    username: alerts
    password: alerts
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers:
      - localhost:3456
    producer:
      key-serializer: org.springframework.kafka.support.serializer.ToStringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer